direction: down

R: {
  label: |md
    **a business capability — e.g. product catalog**
  |
  shape: rectangle
  style: {
    fill: "#238636"
    stroke: "#2ea043"
    font-color: "#FFFFFF"
    border-radius: 8
    font-size: 16
  }
}

P0: {
  label: |md
    something the business does to generate value
  |
  shape: rectangle
  style: {
    fill: "#1f6feb"
    stroke: "#388bfd"
    font-color: "#FFFFFF"
    border-radius: 6
    font-size: 15
  }
}

P1: {
  label: |md
    maps to a business object — Product
  |
  shape: rectangle
  style: {
    fill: "#1f6feb"
    stroke: "#388bfd"
    font-color: "#FFFFFF"
    border-radius: 6
    font-size: 15
  }
}

R -> P0: "1. comprises"
R -> P1: "2. comprises"
