direction: down

S0: {
  label: |md
    **sender/producer**
  |
  shape: rectangle
  style: {
    fill: "#238636"
    stroke: "#2ea043"
    font-color: "#FFFFFF"
    border-radius: 6
    font-size: 16
  }
}

S1: {
  label: |md
    **message channel**

    broker
  |
  shape: rectangle
  style: {
    fill: "#1f6feb"
    stroke: "#388bfd"
    font-color: "#FFFFFF"
    border-radius: 6
    font-size: 16
  }
}

S2: {
  label: |md
    **receiver/consumer**
  |
  shape: rectangle
  style: {
    fill: "#8250df"
    stroke: "#8250df"
    font-color: "#FFFFFF"
    border-radius: 6
    font-size: 16
  }
}

S0 -> S1: "1. sender/producer"
S1 -> S2: "2. broker"
