direction: down

S0: {
  label: |md
    **command**
  |
  shape: rectangle
  style: {
    fill: "#238636"
    stroke: "#2ea043"
    font-color: "#FFFFFF"
    border-radius: 6
    font-size: 16
  }
}

S1: {
  label: |md
    **event store**

    append
  |
  shape: rectangle
  style: {
    fill: "#1f6feb"
    stroke: "#388bfd"
    font-color: "#FFFFFF"
    border-radius: 6
    font-size: 16
  }
}

S2: {
  label: |md
    **projector/event handler**
  |
  shape: rectangle
  style: {
    fill: "#1f6feb"
    stroke: "#388bfd"
    font-color: "#FFFFFF"
    border-radius: 6
    font-size: 16
  }
}

S3: {
  label: |md
    **read model**
  |
  shape: rectangle
  style: {
    fill: "#1f6feb"
    stroke: "#388bfd"
    font-color: "#FFFFFF"
    border-radius: 6
    font-size: 16
  }
}

S4: {
  label: |md
    **query**
  |
  shape: rectangle
  style: {
    fill: "#8250df"
    stroke: "#8250df"
    font-color: "#FFFFFF"
    border-radius: 6
    font-size: 16
  }
}

S0 -> S1: "1. command"
S1 -> S2: "2. append"
S2 -> S3: "3. projector/event handler"
S3 -> S4: "4. read model"
